# Generated by Django 4.1.2 on 2022-12-26 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApiRest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Animal',
        ),
        migrations.DeleteModel(
            name='Emp',
        ),
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
