# Generated by Django 4.1.2 on 2022-12-01 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('celular', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=10)),
                ('sexo', models.CharField(max_length=50)),
            ],
        ),
    ]
