# Generated by Django 4.1.2 on 2022-12-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0002_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('edad', models.CharField(max_length=50)),
                ('cargo', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
    ]
