# Generated by Django 4.1.2 on 2022-12-02 00:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0003_emp'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='dueño',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinica.persona'),
        ),
        migrations.AddField(
            model_name='animal',
            name='veterinario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Clinica.emp'),
        ),
    ]
