# Generated by Django 4.1.2 on 2022-12-02 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0004_animal_dueño_animal_veterinario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emp',
            options={'ordering': ['cargo'], 'verbose_name': 'Emp', 'verbose_name_plural': 'Emps'},
        ),
        migrations.AlterModelTable(
            name='emp',
            table='Emp',
        ),
    ]
