# Generated by Django 4.1.2 on 2022-12-02 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0005_alter_emp_options_alter_emp_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'ordering': ['nombre'], 'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelTable(
            name='persona',
            table='Persona',
        ),
    ]
