# Generated by Django 4.1.2 on 2022-12-02 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0006_alter_persona_options_alter_persona_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emp',
            options={'ordering': ['nombre'], 'verbose_name': 'Emp', 'verbose_name_plural': 'Emps'},
        ),
    ]
