# Generated by Django 4.1.2 on 2022-12-26 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Clinica', '0007_alter_emp_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emp',
            options={},
        ),
        migrations.AlterModelOptions(
            name='persona',
            options={},
        ),
        migrations.AlterModelTable(
            name='emp',
            table=None,
        ),
        migrations.AlterModelTable(
            name='persona',
            table=None,
        ),
    ]
